version: "2.2"
services:
  web_ciavs:
    build: ./
    ports: 
      - 8080:80
      - 8043:443
    volumes:
      - ./php:/var/www/html
  db_ciavs:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes: 
      - './mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=ciava